# TODO(jlewi): This kustomization.yaml is deprecated. We want the
# base_v3 version. This version uses a bunch of problematic patterns e.g.
# i) Using vars to do command line substitution
# ii) Not using a configmap to make application and global config available
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: profiles-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: profiles-

# Labels to add to all resources and selectors.
commonLabels:
  app: profiles
  app.kubernetes.io/component: profiles
  app.kubernetes.io/name: profile-controller
  app.kubernetes.io/part-of: kubeflow-dashboard
  app.kubernetes.io/managed-by: kustomize

resources:
  - crd
  - rbac
  - manager
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
# - webhook

# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
# components:
#   - ../components/prometheus

patchesStrategicMerge:
  - patches/manager.yaml
# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, comment manager_auth_proxy_patch.yaml and
# uncomment manager_prometheus_metrics_patch.yaml.
# - patches/manager_auth_proxy_patch.yaml
# - patches/manager_prometheus_metrics_patch.yaml

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
# - patches/manager_webhook_patch.yaml

# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'.
# Uncomment 'CERTMANAGER' sections in base/crd/kustomization.yaml to enable the CA injection in the admission webhooks.
# 'CERTMANAGER' needs to be enabled to use ca injection
# - patches/webhookcainjection_patch.yaml

# the following config is for teaching kustomize how to do var substitution
vars:
# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER' prefix.
# - name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
#   objref:
#     kind: Certificate
#     group: cert-manager.io
#     version: v1
#     name: serving-cert # this name should match the one in certificate.yaml
#   fieldref:
#     fieldpath: metadata.namespace
# - name: CERTIFICATE_NAME
#   objref:
#     kind: Certificate
#     group: cert-manager.io
#     version: v1
#     name: serving-cert # this name should match the one in certificate.yaml
# - name: SERVICE_NAMESPACE # namespace of the service
#   objref:
#     kind: Service
#     version: v1
#     name: webhook-service
#   fieldref:
#     fieldpath: metadata.namespace
# - name: SERVICE_NAME
#   objref:
#     kind: Service
#     version: v1
#     name: webhook-service

images:
  - name: ghcr.io/kubeflow/dashboard/profile-controller
    newName: ghcr.io/kubeflow/dashboard/profile-controller
    newTag: latest

configMapGenerator:
  - name: namespace-labels-data
    files:
      - namespace-labels.yaml
