apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: poddefaults-webhook-mutating-webhook-configuration
webhooks:
  - name: poddefaults.kubeflow.org
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: poddefaults-webhook-service
        namespace: kubeflow
        path: /apply-poddefault
      caBundle: ""
    namespaceSelector:
      matchLabels:
        app.kubernetes.io/part-of: kubeflow-profile
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]


