apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: poddefaults-webhook-cert
  labels:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
spec:
  isCA: true
  # SERVICE_NAME and SERVICE_NAMESPACE will be substituted by kustomize
  commonName: SERVICE_NAME.SERVICE_NAMESPACE.svc
  dnsNames:
  - SERVICE_NAME.SERVICE_NAMESPACE.svc
  - SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: poddefaults-webhook-selfsigned-issuer
  secretName: poddefaults-webhook-certs

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: poddefaults-webhook-selfsigned-issuer
  labels:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
spec:
  selfSigned: {}
