apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - certificate.yaml
configurations:
  - params.yaml
patches:
  - path: mutating-webhook-configuration.yaml
  - path: deployment.yaml
