apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: poddefaults-webhook-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/poddefaults-webhook-cert
