apiVersion: v1
kind: Service
metadata:
  name: profiles-kfam
spec:
  selector:
    app.kubernetes.io/component: controller-manager
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
