apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - auth_proxy_client_clusterrole.yaml
  - auth_proxy_role.yaml
  - auth_proxy_role_binding.yaml
  - auth_proxy_service.yaml
  - monitor.yaml

patches:
  # This patch enables Prometheus scraping for the manager pod
  - path: manager_prometheus_metrics_patch.yaml
