# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default.

resources:
  - bases/kubeflow.org_profiles.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
  - path: patches/trivial_conversion_patch.yaml
  # Enable webhook conversion for CRD
  - path: patches/webhook_in_profiles.yaml
  # Enable CA injection for CRD using cert-manager
  - path: patches/cainjection_in_profiles.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# This configuration teaches Kustomize how to process CRDs.
configurations:
  - kustomizeconfig.yaml
