apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: poddefaults-webhook-cert
spec:
  isCA: true
  commonName: REPLACEMENT-SVC-NAME.SVC-NAMESPACE.svc
  dnsNames:
  - REPLACEMENT-SVC-NAME.REPLACEMENT-SVC-NAMESPACE.svc
  - REPLACEMENT-SVC-NAME.SVC-NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: poddefaults-webhook-selfsigned-issuer
  secretName: poddefaults-webhook-certs

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: poddefaults-webhook-selfsigned-issuer
spec:
  selfSigned: {}
