apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: poddefaults-webhook-mutating-webhook-configuration
  labels:
    app: poddefaults-webhook
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/poddefaults-webhook-serving-cert
webhooks:
  - name: poddefaults.kubeflow.org
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: poddefaults-webhook
        namespace: kubeflow
        path: /mutate
      caBundle: ""
    rules:
      - apiGroups: ["kubeflow.org"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["poddefaults"]
    failurePolicy: Fail
