apiVersion: apps/v1
kind: Deployment
metadata:
  name: poddefaults-webhook-deployment
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/kubeflow/dashboard/poddefaults-webhook
        name: poddefaults-webhook
        ports:
        - name: https-webhook
          containerPort: 4443
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      serviceAccountName: poddefaults-webhook-service-account
