apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: poddefaults-webhook-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: poddefaults-webhook-cluster-role
subjects:
- kind: ServiceAccount
  name: poddefaults-webhook-service-account
