apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: profiles-system

resources:
  - ../../base

components:
  # NOTE: the common component should always be last, to ensure it labels all resources.
  - ../../components/common
