apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - virtual-service.yaml
  - authorizationpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/component: profile-controller

configurations:
  - params.yaml
