apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: profiles-kfam
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /kfam/
    rewrite:
      uri: /kfam/
    route:
    - destination:
        host: KFAM_SERVICE_NAME.KFAM_SERVICE_NAMESPACE.svc.cluster.local
        port:
          number: 8081
