apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
- ../../base
- virtual-service.yaml

components:
- ../../components/remove-system-namespace
- ../../components/kfam

commonLabels:
  kustomize.component: profiles

configurations:
- params.yaml

vars:
- name: PROFILES_NAMESPACE
  fieldref:
    fieldpath: metadata.namespace
  objref:
    name: profiles-kfam
    kind: Service
    apiVersion: v1
